app/views/main.py
import os
from functools import wraps
from flask import Blueprint, render_template, request, redirect, url_for, send_file, abort
import datetime as dt
import secrets
from ..helpers import db_save_question, db_retrieve_questions, db_add_answers, db_delete_questions
from ..models import LlcComments, WcComments

TABLES = {"WcComments": WcComments, "LlcComments": LlcComments}

main_bp = Blueprint("main", __name__, "../templates")


def admin_protect(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        secret_key = request.form.get('secret_key') or request.args.get("secret_key")
        if not secret_key or not secrets.compare_digest(secret_key, os.environ.get('admin_key')):
            abort(404)
        return f(*args, **kwargs, secret_key=secret_key)

    return wrapper


@main_bp.route("/")
def index():
    grid_texts = [
        ["Campus Guide",
         "Navigating campus resources shouldn't add to your challenges as a nontraditional student. Your time and "
         "energy are invaluable, and your real-world experience enriches the classroom. Let us help you connect with "
         "resources to support your success."],

        ["Smart Investment",
         "Higher education is a major investment of time and energy. Maximize your return by utilizing free academic "
         "support services. As a nontraditional student, you've made sacrifices to be here; we're committed to helping "
         "you thrive."],

        ["Resource Access",
         "Accessing campus resources should be simple. This guide provides clear details on where to go, when services "
         "are available, and how to use them, so you can focus on succeeding in your studies without extra hassle."],

        ["Resource details",
         "Learn about essential campus services like the Writing Center and Lambda Learning Center. These guides "
         "include appointment scheduling and service details, giving you the confidence to achieve academic excellence."]
    ]

    card_texts = [
        "The Writing Center offers free support to Western students at any stage of the writing process, from "
        "brainstorming to final drafts. Writing consultants work with students in 25- or 50-minute sessions to help "
        "improve writing skills through constructive feedback, whether you're working on research papers, presentations,"
        " applications, or creative pieces.",
        "The Lambda Learning Center (LLC) is a collaborative space where students, tutors, and professors work together"
        " to master concepts in math, computer science, and engineering. Equipped with computers, whiteboards, and study"
        " spaces, the LLC provides both independent and group learning opportunities to help students succeed in their"
        " STEM courses."]

    return render_template("index.html", grid_texts=grid_texts, card_texts=card_texts)


@main_bp.route("/Lamda-Learning-Center")
def llc():
    questions = db_retrieve_questions(LlcComments)
    schedule = [
        ["Monday", "10:00 a.m. - 12:00 p.m., 2:00 p.m. - 6:00 p.m."],
        ["Tuesday", "10:00 a.m. - 12:00 p.m., 2:00 p.m. - 6:00 p.m."],
        ["Wednesday", "10:00 a.m. - 12:00 p.m., 2:00 p.m. - 6:00 p.m."],
        ["Thursday", "10:00 a.m. - 12:00 p.m., 2:00 p.m. - 6:00 p.m."],
        ["Friday", "10:00 a.m. - 12:00 p.m., 2:00 p.m. - 6:00 p.m."]
    ]
    services_grid = [
        ["Learning Environment",
         "The Lambda Learning Center (LLC) offers a collaborative space where students, tutors, and professors work"
         " together to master concepts, find academic success, and explore new ideas in STEM fields."],
        ["Equipped Facilities",
         "The LLC is furnished with computers, dry erase boards, math journals, STEM games, and plenty of room for "
         "individual or group work, all to facilitate engaged learning beyond the classroom."],
        ["Academic Support",
         "At the LLC, students can come to work independently on their homework or team up with classmates, fostering "
         "a community focused on supporting each other's academic achievements."],
        ["Accessible Hours",
         "The LLC is open Monday through Friday, from 10am to 12pm and 2pm to 6pm, providing ample opportunities for"
         " students to utilize the space and resources throughout the week."]
    ]
    location_card = """The LLC is located in the Rady Building at Western Colorado University. Specifically, it is in rooms
                      227, 229, and 231 of the Rady Building To find the LLC, you would need to go to the Rady Building
                      on the Western Colorado University campus. Once inside the Rady Building, you can look for rooms
                      227, 229, and 231, which is where the LLC is housed."""

    return render_template("llc.html", schedule=schedule, services_grid=services_grid,
                           location_card=location_card, questions=questions)


@main_bp.route("/LLC-submission", methods=["POST"])
def submit_llc():
    form_data = request.form.to_dict()
    db_save_question(name=form_data['name'], question=form_data['question'], table=LlcComments, date=dt.datetime.now())
    return redirect(url_for('main.llc'))


@main_bp.route("/Writing-Center")
def wc():
    questions = db_retrieve_questions(WcComments)
    schedule = [
        ["Sunday", "4:00 - 7:30 p.m."],
        ["Monday", "1:00 - 6:00 p.m."],
        ["Tuesday", "1:00 - 8:00 p.m."],
        ["Wednesday", "Noon - 8:00 p.m."],
        ["Thursday", "2:00 - 8:00 p.m."],
        ["Friday", "1:00 - 5:00 p.m."],
        ["Saturday", "CLOSED"]
    ]
    services_grid = [
        [
            "Writing Help",
            "The Writing Center offers in-person and online sessions, lasting 25 or 50 minutes, to support students"
            " at any stage of the writing process. Consultants provide feedback on brainstorming, revisions, research "
            "papers, presentations, applications, and creative work without simply editing papers."
        ],
        [
            "Workspace Access",
            "Located in Taylor 112D, the Writing Center provides a welcoming space for students to focus on writing. "
            "Equipped with handbooks, style guides, and online resources, it allows independent skill improvement with"
            " help available if needed."
        ],
        [
            "Essay Guidance",
            "The Writing Center helps students understand assignments, develop ideas, and plan essays. Consultants "
            "highlight strengths, suggest improvements, and teach self-editing techniques to build better writing "
            "habits for academic success."
        ],
        [
            "Flexible Hours",
            "Offering walk-in, scheduled, and online sessions, the Writing Center ensures accessibility with extensive"
            " hours six days a week. Evening weekday availability and Sunday hours accommodate diverse student "
            "schedules for convenient support."
        ]
    ]

    location_card = """The Writing Center is located in Taylor 112D at Western Colorado University's campus in Gunnison, 
                         CO. Students can find help at 1 Western Way, Gunnison, CO 81231. For questions or assistance, the
                         center can be reached by phone at 970.943.7079 or by email at writingcenter@western.edu. The
                         center is directed by Jennifer Foster Caldwell, M.A., who serves as both a Lecturer in English
                         and the Writing Center Director."""
    return render_template("wc.html", schedule=schedule, services_grid=services_grid,
                           location_card=location_card, questions=questions)


@main_bp.route("/WC-submission", methods=["POST"])
def submit_wc():
    form_data = request.form.to_dict()
    db_save_question(name=form_data['name'], question=form_data['question'], table=WcComments, date=dt.datetime.now())
    return redirect(url_for('main.wc'))


@main_bp.route("/Works-Cited")
def works_cited():
    path = "./static/works-cited.pdf"
    return send_file(path, mimetype="application/pdf", as_attachment=False)


@main_bp.route("/Admin")
@admin_protect
def admin(secret_key=None):
    questions = db_retrieve_questions(WcComments, LlcComments)
    print(questions)
    return render_template("admin.html", questions=questions, admin=True, secret_key=secret_key)


@main_bp.route("/Admin-Post", methods=["POST"])
@admin_protect
def admin_post(secret_key=None):
    form_data = request.form.to_dict()

    del form_data['secret_key']
    del form_data['csrf_token']

    to_add = []
    for key, value in form_data.items():
        table_name, table_id = key.split("-")
        answer = value
        to_add.append([TABLES[table_name], table_id, answer])
    print(to_add)
    db_add_answers(to_add)
    return redirect(url_for('main.admin', secret_key=secret_key))


@main_bp.route("/Delete-Question", methods=["POST"])
@admin_protect
def delete_questions(secret_key=None):
    form_data = request.form.to_dict()

    del form_data['secret_key']
    del form_data['csrf_token']

    to_delete = []
    for key, value in form_data.items():
        table_name, table_id = key.split("-")
        to_delete.append([TABLES[table_name], table_id])
    db_delete_questions(to_delete)
    return redirect(url_for('main.admin', secret_key=secret_key))

app/templates/admin.html
{% extends "base.html" %}

{% from "components.html" import comment_board %}
{% block body %}
    <div class="flex justify-center items-center w-screen h-screen">
        {{ comment_board(questions=questions,action=url_for('main.admin_post'), admin=admin, secret_key=secret_key,
    CSRF_TOKEN=CSRF_TOKEN) }}
    </div>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{{ url_for('static', filename='css/output.css') }}" rel="stylesheet"/>
</head>
<body class="bg-dark-navy">
<nav class="fixed top-0 flex flex-row items-center w-screen sm:text-xl lg:text-lg lg:h-[7vh] sm:h-[5vh] p-2 bg-gray-500 text-black z-50 border-b-2 border-accent-gold">
    <img class="h-3/4" src="{{ url_for('static', filename='svg/WCU_logo.svg') }}"
         alt="Wester Colorado University Logo"/>
    <a class="ml-20 link" href="{{ url_for('main.index') }}">Home</a>
    <a class="ml-10 link" href="{{ url_for('main.wc') }}">Writing Center</a>
    <a class="ml-10 link" href="{{ url_for('main.llc') }}">LLC</a>
    <a class="ml-10 link" href="{{ url_for('main.works_cited') }}">Works Cited</a>
</nav>
{% block body %}
{% endblock %}
<script src="{{ url_for('static', filename='javascript/card-transition.js') }}"></script>
</body>
</html>

app/templates/components.html
{% macro hero(text, url) %}
    <section class="relative flex justify-center items-center w-screen lg:h-[60vh] sm:h-[50vh]">
        <img class="absolute object-cover object-top w-full h-full opacity-75" src="{{ url }}"/>
        <h1 class="text-5xl font-bold text-white drop-shadow-lg tracking-wide">{{ text }}</h1>
    </section>
{% endmacro %}

{% macro grid(svgs, texts) %}
    <div id='grid' class="lg:w-[60vw] sm:w-[90vw] h-fit grid lg:grid-cols-2 sm:grid-cols-1 m-3">
        {% for i in range(4) %}
            <div class="relative border-white -m-[.5px] p-5 {% if i < 2 %} border-b {% else %} border-t {% endif %}
            {% if i % 2 == 0 %} border-r {% else %} border-l{% endif %} hover:scale-110 hover:z-40
            hover:bg-gradient-to-tr hover:from-gray-light hover:to-gray-dark hover:shadow-lg
            {{ ['origin-bottom-right', 'origin-bottom-left', 'origin-top-right', 'origin-top-left'][i] }}
                 duration-500">
                <div class="relative top-0 left-0 sm:w-[6vw] lg:w-[3vw] bg-gray-50 rounded-full p-2">
                    <img class="w-full"
                         src="{{ url_for('static', filename='svg/' + svgs[i]) }}" alt="icon">
                </div>
                <h2 class="text-center title font-bold text-white-text mt-3 mb-3 tracking-tight">{{ texts[i][0] }}</h2>
                <p class="par leading-relaxed text-gray-200 font-normal font-sans m-5">{{ texts[i][1] }}</p>
            </div>
        {% endfor %}
    </div>
{% endmacro %}

{% macro card(image, title, par, href, content, border) %}
    {% if href %}<a id="card" href="{{ href }}"> {% endif %}
<div class="border-{{ border }} border-2 flex flex-col items-center sm:w-[80vw] lg:w-[40vw] h-fit rounded-lg bg-gray-light">
    <div class="relative flex justify-center items-center w-full h-fit">
        <img class="w-full object-contain opacity-70 rounded-t-lg" src="{{ image }}"/>
        <div class="absolute w-full m-auto z-40 text-center">
            <h1 class="title font-bold text-white-text tracking-tight">{{ title }} </h1>
            {% if href %}
                <p class="w-full text-base mt-2 bg-white bg-opacity-50">Click on card to learn more!</p>{% endif %}
        </div>
    </div>
    {% if par %}
        <p class="par leading-relaxed text-gray-200 font-normal font-sans m-5">
            {{ par }}
        </p>
    {% elif content %}
        {{ content }}
    {% endif %}
</div>
{% if href %}</a>{% endif %}
{% endmacro %}

{% macro calender(schedule) %}
    <div class="flex flex-col w-5/6 h-full m-3">
        {% for day in schedule %}
            <div class="flex flex-row w-full h-1/7 border-2 border-accent-gold p-2
            {% if loop.index % 2 == 0 %}bg-gray-light{% else %}bg-gray-dark{% endif %}">
                <h2 class="text-lg font-medium text-white-text tracking-tight border-r border-accent-gold w-1/3">{{ day[0] }}</h2>
                <p class="flex items-center ml-8 text-sm leading-relaxed text-gray-200 font-normal font-sans">{{ day[1] }}</p>
            </div>
        {% endfor %}
    </div>
{% endmacro %}

{% macro comment_board(questions, action, admin, secret_key, CSRF_TOKEN) %}

    <div class="w-screen flex flex-col items-center justify-center lg:h-[80vh] sm:h-[40vh] bg-gray-light p-10 border-2
    border-accent-gold">
        <h1 class="title text-center font-sans tracking-tight text-white-text underline my-7">Q & A</h1>
        <div class="flex flex-row sm:w-[90vw] lg:w-5/6 h-full rounded-md p-5 bg-gray-dark">
            <div class="py-6 w-1/2 h-full overflow-y-scroll">
                <h1 class="title text-center font-sans tracking-tight text-white-text mb-7"></h1>
                {% if questions %}
                    {% for question in questions %}
                        <div class="flex items-start border-b border-accent-gold">
                            <div class="w-full flex flex-row">
                                <div class="w-1/2 border-r border-accent-gold p-3">
                                    <h3 class="font-bold text-white-text">Question:</h3>
                                    <p class="ml-5 mt-2 text-white-text opacity-75">{{ question[0] }} asks,</p>
                                    <p class="ml-5 text-white-text opacity-90">{{ question[1] }}</p>
                                </div>
                                <div class="w-1/2 p-3">
                                    {% if admin %}
                                        <form action="{{ url_for('main.delete_questions') }}" method="POST"
                                              class="p-2 bg-red rounded-full">
                                            <input type="hidden" name="csrf_token" value="{{ CSRF_TOKEN }}">
                                            <input type="hidden" name="secret_key" value="{{ secret_key }}">
                                            <input type="hidden" name="{{ question[4] }}-{{ question[3] }}">

                                            <button type="submit" class="">
                                                x
                                            </button>
                                        </form>
                                    {% endif %}
                                    <h3 class="font-bold text-white-text">Answer:</h3>
                                    <p class="ml-5 mt-2 text-white-text opacity-75">{{ question[2] }}</p>
                                </div>


                            </div>
                        </div>


                        {% if admin %}
                            <form action="{{ action }}" method="POST">
                                <input type="hidden" name="csrf_token" value="{{ CSRF_TOKEN }}">
                                <input type="hidden" name="secret_key" value="{{ secret_key }}">
                                <label for="{{ question[4] }}-{{ question[3] }}"
                                       class="block text-sm font-medium text-gray-700">Answer:</label>
                                <textarea
                                        name="{{ question[4] }}-{{ question[3] }}"
                                        placeholder="Enter your question..."
                                        rows="4"
                                        class="w-full mt-3 px-4 py-2 border border-gray-300 rounded-md focus:ring-2
                                focus:ring-blue-500
                                focus:border-blue-500 placeholder-gray-400"></textarea>
                                <button
                                        type="submit"
                                        class="w-fit px-4 py-2 text-white bg-blue-500 rounded-md hover:bg-blue-600 focus:outline-none
                                focus:ring-2 focus:ring-blue-300 transition duration-150 ease-in-out">
                                    Add Answer
                                </button>
                            </form>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <h3 class="w-full h-full flex justify-center items-center font-bold text-gray-800">No questions
                                                                                                       yet!</h3>
                {% endif %}

            </div>
            {% if not admin %}
                <div class="p-6 flex-grow h-full">
                    <h1 class="title text-center font-sans tracking-tight text-white-text">Ask a question.</h1>
                    <form action="{{ action }}" method="POST" class="space-y-6">
                        <input type="hidden" name="csrf_token" value="{{ CSRF_TOKEN }}">
                        <div class="space-y-2">
                            <label for="name" class="block text-sm font-medium text-white-text">Name:</label>
                            <input
                                    type="text"
                                    name="name"
                                    id="name"
                                    placeholder="Enter your name"
                                    required
                                    class="w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500
                            focus:border-blue-500 placeholder-gray-400">
                        </div>
                        <div class="space-y-2">
                            <label for="question" class="block text-sm font-medium text-white-text">Question:</label>
                            <textarea
                                    name="question"
                                    id="question"
                                    placeholder="Enter your question..."
                                    rows="8"
                                    required
                                    class="w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2
                                    focus:ring-blue-500
                            focus:border-blue-500 placeholder-gray-400"></textarea>
                        </div>
                        <button
                                type="submit"
                                class="w-fit px-4 py-2 text-white bg-blue-500 rounded-md hover:bg-blue-600 focus:outline-none
                        focus:ring-2 focus:ring-blue-300 transition duration-150 ease-in-out">
                            Add Question
                        </button>
                    </form>
                </div>

            {% endif %}
        </div>
    </div>
{% endmacro %}

app/templates/index.html
{% extends "base.html" %}
{% from "components.html" import hero, grid, card %}

{% block body %}
    {{ hero("WCU Resource Guide", url_for('static', filename='images/index-hero.jpg')) }}
    <section class="flex flex-col justify-center items-center space-y-24 mt-16 mb-16">

        {{ grid(['people.svg', 'money.svg', 'map.svg', 'examine.svg'], grid_texts) }}
        <div class="relative w-full h-fit overflow-hidden">
            <!-- Carousel container -->
            <div class="flex transition-transform duration-500" id="carousel">
                <!-- Cards side by side -->
                <div id="card-WC" class="flex justify-center w-full flex-shrink-0">
                    {{ card(url_for('static', filename='images/Writing Center.jpg'), "Writing Center", card_texts[0], border='accent-red', href=url_for('main.wc')) }}
                </div>
                <div id="card-LLC" class="flex justify-center w-full flex-shrink-0">
                    {{ card(url_for('static', filename='images/LLC.jpg'), "Lambda Learning Center", card_texts[1], border='accent-gold', href=url_for('main.llc')) }}
                </div>
            </div>

            <!-- Chevrons -->
            <img id="chevron-right" onclick="slideCards('right')"
                 class="absolute w-[2vw] sm:right-10 lg:right-60 top-1/2 -translate-y-1/2 hover:scale-125 duration-1000 rounded-full cursor-pointer z-10"
                 src="{{ url_for('static', filename='svg/chevron-right.svg') }}"/>
            <img id="chevron-left" onclick="slideCards('left')"
                 class="rotate-180 absolute w-[2vw] sm:left-10 lg:left-60 top-1/2 -translate-y-1/2 hover:scale-125 duration-1000 rounded-full cursor-pointer z-10"
                 src="{{ url_for('static', filename='svg/chevron-right.svg') }}"
                 style="opacity:0;"/>
        </div>

    </section>

{% endblock %}

app/templates/llc.html
{% extends "base.html" %}
{% from "components.html" import hero, card, grid, calender, comment_board %}


{% block body %}
    {{ hero("Lamda Learning Center", url_for('static', filename='images/llc-page.jpg')) }}
    <div class="flex flex-col justify-center items-center w-full h-fit space-y-32 mt-20">

        {{ grid(['brain.svg', 'tools.svg', 'support.svg', 'hours.svg'], services_grid) }}

        <div class="relative w-full h-fit overflow-hidden">
            <!-- Carousel container -->
            <div class="flex transition-transform duration-500" id="carousel">
                <!-- Cards side by side -->
                <div id="card-WC" class="flex justify-center items-center w-full flex-shrink-0">
                    {{ card(image=url_for('static', filename='images/hours.jpg'), title="Hours", content=calender(schedule), border='accent-gold') }}
                </div>
                <div id="card-LLC" class="flex justify-center items-center w-full flex-shrink-0">
                    {{ card(image=url_for('static', filename='images/LLC.jpg'), title='Location', par=location_card,border='accent-gold' ) }}
                </div>
            </div>

            <!-- Chevrons -->
            <img id="chevron-right" onclick="slideCards('right')"
                 class="absolute w-[2vw] sm:right-10 lg:right-60 top-1/2 -translate-y-1/2 hover:scale-125 duration-1000 rounded-full cursor-pointer z-10"
                 src="{{ url_for('static', filename='svg/chevron-right.svg') }}"/>
            <img id="chevron-left" onclick="slideCards('left')"
                 class="rotate-180 absolute w-[2vw] sm:left-10 lg:left-60 top-1/2 -translate-y-1/2 hover:scale-125 duration-1000 rounded-full cursor-pointer z-10"
                 src="{{ url_for('static', filename='svg/chevron-right.svg') }}"
                 style="opacity:0;"/>
        </div>

        {{ comment_board(questions, url_for('main.submit_llc')) }}

    </div>
{% endblock %}

app/templates/wc.html
{% extends "base.html" %}
{% from "components.html" import hero, card, grid, calender, comment_board %}

{% block body %}
    {{ hero("Writing Center", url_for('static', filename='images/wc-page.jpg')) }}
    <div class="flex flex-col justify-center items-center w-full h-fit space-y-32 mt-20">

        {{ grid(['brain.svg', 'tools.svg', 'support.svg', 'hours.svg'], services_grid) }}

        <div class="relative w-full h-fit overflow-hidden">

            <div class="flex transition-transform duration-500" id="carousel">

                <div id="card-WC" class="flex justify-center items-center w-full flex-shrink-0">
                    {{ card(image=url_for('static', filename='images/hours.jpg'), title="Hours", content=calender(schedule), border='accent-gold') }}
                </div>
                <div id="card-LLC" class="flex justify-center items-center w-full flex-shrink-0">
                    {{ card(image=url_for('static', filename='images/wc-page.jpg'), title='Location', par=location_card,border='accent-gold' ) }}
                </div>
            </div>


            <img id="chevron-right" onclick="slideCards('right')"
                 class="absolute w-[2vw] sm:right-10 lg:right-60 top-1/2 -translate-y-1/2 hover:scale-125 duration-1000 rounded-full cursor-pointer z-10"
                 src="{{ url_for('static', filename='svg/chevron-right.svg') }}"/>
            <img id="chevron-left" onclick="slideCards('left')"
                 class="rotate-180 absolute w-[2vw] sm:left-10 lg:left-60 top-1/2 -translate-y-1/2 hover:scale-125 duration-1000 rounded-full cursor-pointer z-10"
                 src="{{ url_for('static', filename='svg/chevron-right.svg') }}"
                 style="opacity:0;"/>
        </div>

        {{ comment_board(questions, url_for('main.submit_wc')) }}

    </div>
{% endblock %}